spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  datasource:
    url: "jdbc:postgresql://localhost:5432/cfa_jan2023"
    username: postgres
    password: postgres
    properties:
      hibernate:
        format_sql: true

